services:
  docs:
    image: vgmedical_verification_local_docs
    container_name: vgmedical_verification_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./vgmedical_verification:/app/vgmedical_verification:z
    ports:
      - '9000:9000'
    command: /start-docs
