# Generated by Django 5.2.6 on 2025-09-19 19:38

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('internal', 'Reporte Interno'), ('hospital', 'Reporte Hospital'), ('description', 'Descripción Quirúrgica')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_patient_name', models.CharField(blank=True, max_length=255)),
                ('extracted_patient_id', models.CharField(blank=True, max_length=100)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('extracted_city', models.CharField(blank=True, max_length=100)),
                ('extracted_doctor', models.CharField(blank=True, max_length=255)),
                ('extracted_procedure', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyEquivalence',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('canonical_name', models.CharField(max_length=500, unique=True)),
                ('aliases', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('times_used', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurgicalCase',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=100)),
                ('surgery_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=255)),
                ('procedure', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('basic_data_match', models.BooleanField(default=False)),
                ('supplies_match', models.BooleanField(default=False)),
                ('traceability_complete', models.BooleanField(default=False)),
                ('requires_review', models.BooleanField(default=True)),
                ('basic_data_details', models.JSONField(default=dict)),
                ('supplies_details', models.JSONField(default=dict)),
                ('traceability_details', models.JSONField(default=dict)),
                ('discrepancies', models.JSONField(default=list)),
                ('verification_score', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('analyst_feedback', models.JSONField(blank=True, default=dict)),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(blank=True, max_length=500)),
                ('quantity', models.IntegerField()),
                ('ref_code', models.CharField(blank=True, max_length=100)),
                ('lot_code', models.CharField(blank=True, max_length=100)),
                ('udi_label_present', models.BooleanField(default=False)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='document_processor.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
