# Generated by Django 5.2.6 on 2025-09-19 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_processor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyequivalence',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='surgical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_processor.surgicalcase'),
        ),
        migrations.AddField(
            model_name='verificationresult',
            name='feedback_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationresult',
            name='surgical_case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='document_processor.surgicalcase'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('surgical_case', 'document_type')},
        ),
    ]
